# tbump config sets baseVersion in chartpress.yaml
[version]
current = "1.0.0-0.dev"

# match our prerelease prefixes
# -alpha.1
# -beta.2
# -0.dev

regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (\-
    (?P<prelease>
      (
       (alpha|beta|rc)\.\d+|
       0\.dev
      )
    )
  )?
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "{new_version}"

# For each file to patch, add a [[file]] config
# section containing the path of the file, relative to the
# tbump.toml location.
[[file]]
src = "chartpress.yaml"
search = 'baseVersion: "{current_version}"'