# Volume definition to set up a NFS volume for JupyterHub to store users' home directories.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterhub-home-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # TODO: Replace this with the address of the in-cluster NFS server created by JupyterHub-Home-NFS
    server: home-nfs.jupyterhub-home-nfs.svc.cluster.local # <--- REPLACE WITH YOUR NFS SERVER ADDRESS
    path: /
  mountOptions:
    - rsize=1048576
    - wsize=1048576
    - timeo=600
    - soft # We pick soft over hard, so NFS lockups don't lead to hung processes
    - retrans=2
    - noresvport
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-nfs
spec:
  accessModes:
    - ReadWriteMany
  volumeName: jupyterhub-home-nfs
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
