apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jupyterhub-home-nfs.home-nfs.fullname" . }}-ganesha-config
data:
  ganesha.conf: |
    {{ .Values.nfsServer.extraGaneshaConfig | nindent 4 }}
    {{- if .Values.nfsServer.qos.enabled }}
    QOS_DEFAULT_CONFIG {
        enable_qos = true;

        # We only use Ganesha with one export, 
        # so only set this on client vs. per_export_per_client
        qos_type = "Per_Client";

        {{- with .Values.nfsServer.qos.bandwidth }}
        {{- if .enabled }}
        {{- if not (empty .combined) }}
        enable_bw_control = true;
        combined_rw_bw_control = true;
        {- /* Max Bandwidth is smaller than max int64 */}
        max_client_combined_bw = {{ int64 .combined }};      
        {{- else }}
        enable_bw_control = true;
        {{- if not (empty .read) }}
        max_client_read_bw = {{ int64 .read }};      
        {{- end }}
        {{- if not (empty .write) }}
        max_client_write_bw = {{ int64 .write }};   
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}

        {{- with .Values.nfsServer.qos.iops }}
        {{- if .enabled }}
        {{- if not (empty .combined) }}
        enable_iops_control = true;
        combined_rw_iops_control = true;
        max_client_combined_iops = {{ int64 .combined }};      
        {{- else }}
        enable_iops_control = true;
        {{- if not (empty .read) }}
        max_client_read_iops = {{ int64 .read }};      
        {{- end }}
        {{- if not (empty .write) }}
        max_client_write_iops = {{ int64 .write }};   
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
    }
    {{- end }}
    EXPORT
    {
        # Export Id (mandatory, each EXPORT must have a unique Export_Id)
        Export_Id = 1;

        # Exported path (mandatory)
        Path = /export;

        # Pseudo Path (for NFS v4)
        Pseudo = /;

        # Client access control options
        CLIENT
        {
            Clients = {{ if .Values.nfsServer.enableClientAllowlist }}{{ .Values.nfsServer.allowedClients | join "," }}{{ else }}*{{ end }};
            Anonymous_uid = {{ .Values.quotaEnforcer.config.QuotaManager.uid }};
            Anonymous_gid = {{ .Values.quotaEnforcer.config.QuotaManager.gid }};
            Access_Type = RW;
            Squash = All_Squash;
            SecType = "sys";
        }

        # NFS protocol options
        Transports = TCP;
        Protocols = 3, 4;

        SecType = "sys";

        # Exporting FSAL
        FSAL {
            Name = VFS;
        }
    }

    NFSv4 {
        # During the startup grace period, the NFS server only accepts recovery
        # related operations, and will block normal operations. It is a
        # mechanism to avoid corruption issues by allowing clients to finalize
        # things they had a lease for before they lost connectivity, allowing
        # other clients to start doing new things.
        #
        # Lease_Lifetime defaults to 60, and Grace_Period to 90. We retain the
        # 1.5 ratio as their relative proportions was of importance.
        #
        Lease_Lifetime = 20;
        Grace_Period = 30;
    }
