{{- if or .Values.eks.enabled .Values.gke.enabled .Values.openstack.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-nfs-home-directories-volume
  {{- if .Values.persistentVolume.addStandardLabels }}
  labels:
    {{- include "jupyterhub-home-nfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
  {{- end }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  volumeMode: Filesystem
  accessModes:
    {{- toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  {{- if .Values.eks.enabled }}
  csi:
    driver: ebs.csi.aws.com
    fsType: xfs
    volumeHandle: {{ .Values.eks.volumeId }}
  {{- else if .Values.gke.enabled }}
  csi:
    driver: pd.csi.storage.gke.io
    fsType: xfs
    volumeHandle: {{ .Values.gke.volumeId }}
  {{- else if .Values.openstack.enabled }}
  csi:
    driver: cinder.csi.openstack.org
    fsType: xfs
    volumeHandle: {{ .Values.openstack.volumeId }}
  {{- end }}
  mountOptions:
    - rw
    - relatime
    - nouuid
    - attr2
    - inode64
    - logbufs=8
    - logbsize=32k
    - pquota
{{- end }}
