apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jupyterhub-home-nfs.resourceName" . }}-nfs-home-directories-claim
  labels:
    {{- include "jupyterhub-home-nfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    {{- toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
  storageClassName: ""
  {{- if or .Values.eks.enabled .Values.gke.enabled .Values.openstack.enabled}}
  volumeName: {{ .Release.Name }}-nfs-home-directories-volume
  {{- end }}
