apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-nfs-home-directories-claim
spec:
  accessModes:
    {{- toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
  storageClassName: ""
  {{- if or .Values.eks.enabled .Values.gke.enabled .Values.openstack.enabled}}
  volumeName: {{ .Release.Name }}-nfs-home-directories-volume
  {{- end }}
