{{- /*
  Changes to this rendered manifest triggers a restart of the pods
  as the deployment specification includes an annotation with a checksum of this.
*/ -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "jupyterhub-home-nfs.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- /*
    To restart the pods only when relevant, we pick out the
    chart configuration actually consumed in the mounted quota-enforcer-config.py
    file.
  */}}
  chart-config.yaml: |
    {{- pick .Values.quotaEnforcer "config" "extraConfig" | toYaml | nindent 4 }}

  {{- /* Glob files to allow them to be mounted by the quota enforcer pod */}}
  {{- /* key=filename: value=content */}}
  {{- (.Files.Glob "mounted-files/*").AsConfig | nindent 2 }}
